services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_list_production
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo_list_production -h localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  app:
    build:
      context: ./back-end
    container_name: rails_app
    # command: "./bin/rails db:migrate"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: test
      POSTGRES_HOST: postgres_db
      POSTGRES_USER: postgres
      DATABASE_PASSWORD: postgres
      POSTGRES_DB: todo_list_production
      POSTGRES_PORT: 5432
      BUNDLE_WITHOUT: ""
    volumes:
      - .:/rails:cached
      - rails_cache:/rails/tmp/cache
      - rails_logs:/rails/log
    networks:
      - app_network  
    depends_on:
      postgres_db:
        condition: service_healthy


networks:
  app_network:
    driver: bridge

volumes:
  pg_data:  
  rails_cache:
  rails_logs:
